# Change these first
owner: cyp0633 # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: blog
    url: https://cyp0633.icu
  - name: GitHub proxy
    url: https://gh.cyp0633.icu
  - name: Gitea
    url: https://git.cyp0633.icu
  - name: Cloudreve
    url: https://drive.cyp0633.icu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cyp0633.icu
  # baseUrl: /uptime-monitor
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: cyp0633's Uptime Tracker
  # introMessage: 
  navbar:

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
